In [1]:
# !pip install reportlab
# !pip install xlsxwriter

<div class="alert alert-info">
    Im ersten Abschnitt werden Inputs und Deklarationen festgelegt, sowie In- und Output-Pfade gesetzt, um diese für spätere Verwendungszwecke erneut verwenden zu können. <br><br>
    Ebenfalls wird das anzustrebende Datenschema aufgezeigt und in einer Liste gespeichert, um dieses jederzeit abzurufen und anpassen zu können
</div>

In [2]:
import pandas as pd
import os
import numpy as np

from pathlib import Path
from datetime import datetime

from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors

In [3]:
# -------------------------- Basisverzeichnis ----------------------------
base_dir = os.getcwd()

# --------------- Eingabe- und Ausgabeordner definieren ------------------
input_path = os.path.join(base_dir, "Gesammelte_Datenbanken")
output_path = os.path.join(base_dir, "Angepasste_Datenbanken")
data_scheme_path = os.path.join(base_dir, "globales_Datenschema")

print("Input-Pfad:", input_path)
print("Output-Pfad:", output_path)
print("Output-Pfad:", data_scheme_path)

Input-Pfad: C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\Gesammelte_Datenbanken
Output-Pfad: C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\Angepasste_Datenbanken
Output-Pfad: C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\globales_Datenschema

<div class="alert alert-info">
    <b>Zuerst wird eine Liste angelegt mit</b><br>
    - Zielparameter mit Einheit<br>
    - Zielparameter ohne Einheit<br>
    - Einheit des Zielparameters
</div>

In [4]:
# ----------------------- Folgende Attribute werden für die Bachelorarbeit benötigt ------------------
attributes = [
    "location",
    "well_or_spring_name",
    "utm_e",
    "utm_n",
    "depth_bgl_in_m",
    "rock_type",
    "stratigraphic_period",
    "temperature_in_c",
    "electrical_conductivity_25c_in_uS/cm",
    "pH",
    "redox_potential_in_mV",
    "total_dissolved_solids_in_mmol/L", 
    "O2_in_mmol/L",
    "Na_in_mmol/L",
    "Mg_in_mmol/L",
    "Ca_in_mmol/L",
    "Cl_in_mmol/L",
    "SO4_in_mmol/L",
    "HCO3_in_mmol/L",
    "Li_in_mmol/L",
    "K_in_mmol/L",
    "Sr_in_umol/L", # umol
    "NH4_in_umol/L", # umol
    "Fe_in_mmol/L",
    "Mn_in_mmol/L",
    "F_in_umol/L", # umol
    "NO3_in_mmol/L",
    "H2SiO3_in_umol/L", # umol
    "HS_in_mmol/L"
]

# mmol = milli-Mol
# umol = Mikro-Mol


# ---------------------------------- 2. Spalte mit Entfernung aller Suffixe ------------------------------------
suffixes = {
    "_in_mmol/L": "mmol/L",
    "_in_umol/L": "µmol/L",
    "_in_mV": "mV",
    "_in_m": "m",
    "_in_c": "°C",
    "_in_uS/cm": "µS/cm"
}

simplified = []
units = []

for a in attributes:
    clean = a
    unit = ""
    for s, u in suffixes.items():
        if s in a:
            clean = clean.replace(s, "")
            unit = u
            break
    simplified.append(clean)
    units.append(unit)
    
# ---------------------------------- Zusammengefügtes Array mit zwei Spalten -----------------------------------
target_structure = np.array(list(zip(attributes, simplified, units)))


# --------------------------------------------- Anzeigen -------------------------------------------------------
import pandas as pd
pd.DataFrame(target_structure, columns=["Original", "Simplified", "Unit"])

                                Original                   Simplified    Unit
0                               location                     location
1                    well_or_spring_name          well_or_spring_name
2                                  utm_e                        utm_e
3                                  utm_n                        utm_n
4                         depth_bgl_in_m                    depth_bgl       m
5                              rock_type                    rock_type
6                   stratigraphic_period         stratigraphic_period
7                       temperature_in_c                  temperature      °C
8   electrical_conductivity_25c_in_uS/cm  electrical_conductivity_25c   µS/cm
9                                     pH                           pH
10                 redox_potential_in_mV              redox_potential      mV
11      total_dissolved_solids_in_mmol/L       total_dissolved_solids  mmol/L
12                          O2_in_mmol/L                           O2  mmol/L
13                          Na_in_mmol/L                           Na  mmol/L
14                          Mg_in_mmol/L                           Mg  mmol/L
15                          Ca_in_mmol/L                           Ca  mmol/L
16                          Cl_in_mmol/L                           Cl  mmol/L
17                         SO4_in_mmol/L                          SO4  mmol/L
18                        HCO3_in_mmol/L                         HCO3  mmol/L
19                          Li_in_mmol/L                           Li  mmol/L
20                           K_in_mmol/L                            K  mmol/L
21                          Sr_in_umol/L                           Sr  µmol/L
22                         NH4_in_umol/L                          NH4  µmol/L
23                          Fe_in_mmol/L                           Fe  mmol/L
24                          Mn_in_mmol/L                           Mn  mmol/L
25                           F_in_umol/L                            F  µmol/L
26                         NO3_in_mmol/L                          NO3  mmol/L
27                      H2SiO3_in_umol/L                       H2SiO3  µmol/L
28                          HS_in_mmol/L                           HS  mmol/L

<div class="alert alert-info">
    <b>Diese Liste wird ergänzt um</b><br>
    - eine Spalte mit Umrechnungsfaktoren von mg/L in mmol/L oder umol/L<br><br>
    Hierzu werden die Umrechnungsfaktoren
</div>

In [5]:
# ---------------------- Molmassen (g/mol) nach NIST "Standard Atomic Weight"
# ---------------------- https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl?ele=&all=all&ascii=html&isotype=all
MOLAR_MASS = {
    "O2": 31.9988,
    "Na": 22.989769,
    "Mg": 24.305,
    "Ca": 40.078,
    "Cl": 35.45,
    "SO4": 96.06,
    "HCO3": 61.0168,
    "Li": 6.94,
    "K": 39.0983,
    "Sr": 87.62,
    "NH4": 18.038,
    "Fe": 55.845,
    "Mn": 54.938,
    "F": 18.998,
    "NO3": 62.0049,
    "H2SiO3": 78.11,
    "HS": 33.07
}

# ------------------------------ Umrechnungsfaktoren berechnen (Umrechnung von mg/L in mmol/L oder µmol/L --------
conversion_factors = []

for orig, simp, unit in target_structure:
    if unit in ["mmol/L", "µmol/L"] and simp in MOLAR_MASS:
        M = MOLAR_MASS[simp]
        if unit == "mmol/L":
            factor = 1000 / M       # ------ mg/L in mmol/L
        elif unit == "µmol/L":
            factor = 1_000_000 / M  # ------ mg/L in µmol/L
    else:
        factor = ""
    conversion_factors.append(factor)

# ---------------------------------------- Neues Array mit 4 Spalten ----------------------------------------------
target_structure_extended = np.array(list(zip(
    target_structure[:, 0],
    target_structure[:, 1],
    target_structure[:, 2],
    conversion_factors
)))

# --------------------------------------------- Anzeigen ----------------------------------------------------------
pd.DataFrame(target_structure_extended, columns=["Original", "Simplified", "Unit", "Conversion_Factor"])

,Original,Simplified,Unit,Conversion_Factor
0,location,location,,
1,well_or_spring_name,well_or_spring_name,,
2,utm_e,utm_e,,
3,utm_n,utm_n,,
4,depth_bgl_in_m,depth_bgl,m,
5,rock_type,rock_type,,
6,stratigraphic_period,stratigraphic_period,,
7,temperature_in_c,temperature,°C,
8,electrical_conductivity_25c_in_uS/cm,electrical_conductivity_25c,µS/cm,
9,pH,pH,,
10,redox_potential_in_mV,redox_potential,mV,
11,total_dissolved_solids_in_mmol/L,total_dissolved_solids,mmol/L,
12,O2_in_mmol/L,O2,mmol/L,31.251171918946962
13,Na_in_mmol/L,Na,mmol/L,43.497609741098316
14,Mg_in_mmol/L,Mg,mmol/L,41.14379757251594
15,Ca_in_mmol/L,Ca,mmol/L,24.951344877488896
16,Cl_in_mmol/L,Cl,mmol/L,28.208744710860366
17,SO4_in_mmol/L,SO4,mmol/L,10.410160316468874
18,HCO3_in_mmol/L,HCO3,mmol/L,16.38892895071521
19,Li_in_mmol/L,Li,mmol/L,144.0922190201729
20,K_in_mmol/L,K,mmol/L,25.576559594662683
21,Sr_in_umol/L,Sr,µmol/L,11412.91942478886
22,NH4_in_umol/L,NH4,µmol/L,55438.51868278079
23,Fe_in_mmol/L,Fe,mmol/L,17.906706061420003
24,Mn_in_mmol/L,Mn,mmol/L,18.202337180093924
25,F_in_umol/L,F,µmol/L,52637.11969681019
26,NO3_in_mmol/L,NO3,mmol/L,16.12775764496032
27,H2SiO3_in_umol/L,H2SiO3,µmol/L,12802.458071949815
28,HS_in_mmol/L,HS,mmol/L,30.23888720895071

<div class="alert alert-info">
    <b>Erstellen einer .pdf</b><br>
    Diese .pdf dient dazu bei händischer Auswertung der Datenbanken zu vergleichen, welche Attribute in den jeweiligen Dantesätzen vorkommen.
</div>

In [6]:
# Falls target_structure_extended ein NumPy-Array ist → DataFrame machen
if not isinstance(target_structure_extended, pd.DataFrame):
    target_structure_extended = pd.DataFrame(target_structure_extended)

# Daten vorbereiten
data = [target_structure_extended.columns.tolist()] + target_structure_extended.values.tolist()

# Speicherpfad
pdf_path = os.path.join(data_scheme_path, "globales_Datenschema.pdf")

# -------------------------- PDF mit einer Tabelle ---------------------------
doc = SimpleDocTemplate(pdf_path, pagesize=A4)
tbl = Table(data, repeatRows=1)
tbl.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("ALIGN", (0,0), (-1,-1), "CENTER"),
    ("FONTSIZE", (0,0), (-1,-1), 8),
    ("GRID", (0,0), (-1,-1), 0.25, colors.grey),
]))

doc.build([tbl])

print(".pdf Pfad:", pdf_path)

.pdf Pfad: C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\globales_Datenschema\globales_Datenschema.pdf

<div class="alert alert-danger">
    <h1><b>DATENBANK 1</b></h1>
</div>

<div class="alert alert-block alert-warning">
    https://www.reflect-h2020.eu/efa/#form1 <br>
    <b>DATENBANK 1:</b> Komplette REFLECT Datenbank, stand 05.11.2025
</div>

In [7]:
# --------------- Eingabe- und Ausgabeordner definieren ------------------
mid_reflect_path = os.path.join(os.getcwd(), "Zwischenstände", "REFLECT_Datenbank")
print("REFLECT_Datenbank:", mid_reflect_path)

REFLECT_Datenbank: C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\Zwischenstände\REFLECT_Datenbank

In [8]:
# Dateipfad zur REFLECT-Datenbank
reflect_path = os.path.join(input_path, "REFLECT_Horizon_2020-Data_Export_2025-11-05_20-59-36.xlsx")

df_reflect = pd.read_excel(reflect_path)

display(df_reflect)

,fluid_sample_id,well_id,local_id_f,latitude_,longitude_,country,powpl_name,nuts2_name,nuts3_name,date_of_well_completion_year,...,tritium_3h_thousandths,oxigen_18_so4_thousandths,sulfur_34_so4_thousandths,sulfur_34_h2s_thousandths,carbon_13_co2_thousandths,lithium_7_thousandths,boron_11_thousandths,strontium_87sr_per_86sr_thousandths,references_for_fluid_data,remarks_fluid
0,W_AU_001_FS_001,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Analysis GFZ laboratory,N/D
1,W_AU_001_FS_002,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Analysis GFZ laboratory,N/D
2,W_AU_001_FS_003,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Analysis GFZ laboratory,N/D
3,W_AU_001_FS_004,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Hydroisotop GmbH 347619,N/D
4,W_AU_001_FS_005,W_AU_001,Blumau 2,47.120000,16.040000,Austria,N/D,Steiermark,Oststeiermark,N/D,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,Hydroisotop GmbH 347620,N/D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5100,N/D,W_IT_378,MOLINETTO,43.203889,10.856667,Italy,N/D,Toscana,Pisa,1970,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D
5101,N/D,W_IT_379,MOLINETTO 002,43.204167,10.847778,Italy,N/D,Toscana,Pisa,1975,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D
5102,N/D,W_IT_380,MONTEROTONDO 018,43.161111,10.855000,Italy,N/D,Toscana,Pisa,1964,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D
5103,N/D,W_IT_381,NOCCIOLO,43.203333,10.806111,Italy,N/D,Toscana,Pisa,1938,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D
5104,N/D,W_IT_382,OLIVETA,43.201389,10.806944,Italy,N/D,Toscana,Pisa,1939,...,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D,N/D

<div class="alert alert-info">
    <b>Schritt 1 | Manuelles finden der zu verwendenden Daten</b><br>
    Findet von Hand statt - es wird manuell überprüft, welche Spalten des globalen Zielschemas, den Spalten in der Datenbank entsprechen.<br>
    Das Ergebnis dieser Auswertung findet sich in dem Ordner "Zwischenstände" der jeweiligen Datenbank in Form einer Mapping .pdf wieder
</div>

<div class="alert alert-info">
    <b>Schritt 2.1 | Mapping zu Datenschema als .csv Datei</b><br>
    Nachfolgend findet das Mapping der zu verwenden Daten im Bezug auf das globale Datenschema statt. <br>
    Dabei wird die angefertigte .pdf verwendet um die zu mappenden Daten übertragen zu können.<br><br>
    Falls eine Datenspalte nicht vorhanden ist, wird diese ergänzt, jedoch nicht ausgefüllt.
</div>

In [9]:
# ------------------------- Globale Zielstruktur ---------------------------
target_columns = [
    "location",
    "well_or_spring_name",
    "utm_e",
    "utm_n",
    "depth_bgl_in_m",
    "rock_type",
    "stratigraphic_period",
    "temperature_in_c",
    "electrical_conductivity_25c_in_uS/cm",
    "pH",
    "redox_potential_in_mV",
    "total_dissolved_solids_in_mmol/L",
    "O2_in_mmol/L",
    "Na_in_mmol/L",
    "Mg_in_mmol/L",
    "Ca_in_mmol/L",
    "Cl_in_mmol/L",
    "SO4_in_mmol/L",
    "HCO3_in_mmol/L",
    "Li_in_mmol/L",
    "K_in_mmol/L",
    "Sr_in_umol/L",
    "NH4_in_umol/L",
    "Fe_in_mmol/L",
    "Mn_in_mmol/L",
    "F_in_umol/L",
    "NO3_in_mmol/L",
    "H2SiO3_in_umol/L",
    "HS_in_mmol/L",
]

# ---------------------------- Mapping der Spalten je Arbeitsmappe ----------------------------
fluid_map = {
    "nuts2_name": "location",
    "local_id_f": "well_or_spring_name",
    "latitude_": "utm_e",
    "longitude_": "utm_n",
    "well_depth_m": "depth_bgl_in_m",
    "temperature_c": "temperature_in_c",
    "electrical_conductivity_us_per_cm_ec25": "electrical_conductivity_25c_in_uS/cm",
    "ph": "pH",
    "eh_mv": "redox_potential_in_mV",
    "tds_mg_per_l": "total_dissolved_solids_in_mmol/L",
    "dissolved_oxigen_mg_per_l": "O2_in_mmol/L",
    "na_mg_per_l": "Na_in_mmol/L",
    "mg_mg_per_l": "Mg_in_mmol/L",
    "ca_mg_per_l": "Ca_in_mmol/L",
    "cl_mg_per_l": "Cl_in_mmol/L",
    "so4_mg_per_l": "SO4_in_mmol/L",
    "hco3_mg_per_l": "HCO3_in_mmol/L",
    "li_mg_per_l": "Li_in_mmol/L",
    "k_mg_per_l": "K_in_mmol/L",
    "sr_mg_per_l": "Sr_in_umol/L",
    "fe_mg_per_l": "Fe_in_mmol/L",
    "mn_mg_per_l": "Mn_in_mmol/L",
    "f_mg_per_l": "F_in_umol/L",
}

rock_map = {"rock_type": "rock_type"}
reservoir_map = {"age_of_formation": "stratigraphic_period"}


# ----------------------------------- Blattnamen -----------------------------------------------
SHEET_FLUID = "Fluid-well Data Export"
SHEET_ROCK = "Rock-well Data Export"
SHEET_RES = "Reservoir-well Data Export"


# --------------------------------- Datei einlesen ---------------------------------------------
xls = pd.ExcelFile(reflect_path)


# ------------------------------ Blatt einlesen und nur Spalte umbenennen ----------------------
def read_and_map(sheet_name, mapping):
    if sheet_name not in xls.sheet_names:
        return pd.DataFrame()
    df = pd.read_excel(xls, sheet_name=sheet_name)
    rename_cols = {src: tgt for src, tgt in mapping.items() if src in df.columns}
    df = df.rename(columns=rename_cols)
    return df[[*rename_cols.values()]] if rename_cols else pd.DataFrame()


# ---------------------------------- Einlesen und umbenennen ------------------------------------
df_fluid = read_and_map(SHEET_FLUID, fluid_map)
df_rock = read_and_map(SHEET_ROCK, rock_map)
df_res = read_and_map(SHEET_RES, reservoir_map)


# ---------------------------------- Drei Blätter werden aneinander gehangen -------------------
df_combined = pd.concat([df_fluid, df_rock, df_res], axis=1)


# -------------------------------- Check: Doppelte Spaltennamen vermeiden -----------------------
df_combined = df_combined.loc[:, ~df_combined.columns.duplicated()]


# ------------------------------------- Fehlende Spalten ergänzen -------------------------------
for col in target_columns:
    if col not in df_combined.columns:
        df_combined[col] = np.nan


# --------------------------------------- Auf Zielstruktur bringen ------------------------------
df_out = df_combined[target_columns].copy()


# ---------------------------------------------- CSV speichern ----------------------------------
out_reflect_path = os.path.join(mid_reflect_path, "before_conversion_reflect_mapped.csv")
df_out.to_csv(out_reflect_path, index=False, encoding="utf-8-sig")

print(f"REFLECT-Mapping abgeschlossen (auf {len(df_out)} Zeilen)")
print(f".csv Pfad: {out_reflect_path}")

REFLECT-Mapping abgeschlossen (auf 5105 Zeilen)
.csv Pfad: C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\Zwischenstände\REFLECT_Datenbank\before_conversion_reflect_mapped.csv

<div class="alert alert-info">
    <b>Schritt 2.2 | Unwandlung in Excel</b><br>
    Um sich die neu entstandende Datei in Form einer Excel-Tabelle anschauen zu können findet eine Konvertierung der .csv zu .xlsx statt<br><br>
    Dies wird als Funktion verankert, sodass diese immer wieder nach Veränderung der .csv ausgeführt werden kann, um eine Darstellung via Excel zu ermöglichen.
</div>

In [10]:
csv_path = os.path.join(mid_reflect_path, "before_conversion_reflect_mapped.csv")
excel_path = os.path.join(mid_reflect_path, "before_conversion_reflect_mapped_readable.xlsx")

In [11]:
def csv_to_excel(csv_path, excel_path, sheet_name="REFLECT Mapped"):
        
    # ------------------------------ CSV einlesen ---------------------------------
    df = pd.read_csv(csv_path)
        
    # ------------------------- In Excel schreiben ----------------------------------
    with pd.ExcelWriter(excel_path, engine="xlsxwriter") as writer:
        df.to_excel(writer, index=False, sheet_name="REFLECT Mapped")
        
        # ------------------- Zugriff auf Arbeitsmappe ------------------------------
        workbook  = writer.book
        worksheet = writer.sheets["REFLECT Mapped"]
        
        # ---------------------- Spaltenbreite ------------------------------------
        for i, col in enumerate(df.columns):
            max_len = max(df[col].astype(str).map(len).max(), len(col)) + 2
            worksheet.set_column(i, i, max_len)
        
    print(f"Excel Pfad:\n{excel_path}")

In [12]:
# Auskommentieren, wenn dies nur am Ende durchgeführt werden soll
# Einkommentieren, wenn Zwischenstände überprüft werden sollen

# csv_to_excel(csv_path, excel_path)

<div class="alert alert-info">
    <b>Schritt 3 | Umwandlung zu einheitlichem NaN Datentyp</b><br>
    "Leere Elemente" oder solche die mit "N/D" gekennzeichnet sind werde zum Pandas Typ NaN umgewandelt
</div>

In [13]:
df_out = df_out.replace(r'^\s*$|N/D', np.nan, regex=True)
df_out.to_csv(out_reflect_path, index=False, encoding="utf-8-sig")

In [14]:
csv_to_excel(csv_path, excel_path)

Excel Pfad:
C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\Zwischenstände\REFLECT_Datenbank\before_conversion_reflect_mapped_readable.xlsx

<div class="alert alert-info">
    <b>Schritt 4 | Umwandlung der Einheiten</b><br>
    Da die Werte noch nicht in ihrer korrekten Einheit vorliegen (bspw. mmol/L oder umol/L), sondern in ihrer Ausgangsform (oft mg/L) muss im nächsten Schritt genau dies getan werden.
</div>

In [15]:
# -------------------------------------------------------------

# Zielspalten (nur zur Absicherung der Ausgabe)
target_columns = [
    "location",
    "well_or_spring_name",
    "utm_e",
    "utm_n",
    "depth_bgl_in_m",
    "rock_type",
    "stratigraphic_period",
    "temperature_in_c",
    "electrical_conductivity_25c_in_uS/cm",
    "pH",
    "redox_potential_in_mV",
    "total_dissolved_solids_in_mmol/L",
    "O2_in_mmol/L",
    "Na_in_mmol/L",
    "Mg_in_mmol/L",
    "Ca_in_mmol/L",
    "Cl_in_mmol/L",
    "SO4_in_mmol/L",
    "HCO3_in_mmol/L",
    "Li_in_mmol/L",
    "K_in_mmol/L",
    "Sr_in_umol/L",
    "NH4_in_umol/L",
    "Fe_in_mmol/L",
    "Mn_in_mmol/L",
    "F_in_umol/L",
    "NO3_in_mmol/L",
    "H2SiO3_in_umol/L",
    "HS_in_mmol/L",
]

# Molmassen (g/mol)
M = {
    "O2": 31.998,
    "Na": 22.989769,
    "Mg": 24.305,
    "Ca": 40.078,
    "Cl": 35.45,
    "SO4": 96.06,
    "HCO3": 61.0168,
    "Li": 6.94,
    "K": 39.0983,
    "Sr": 87.62,
    "NH4": 18.038,
    "Fe": 55.845,
    "Mn": 54.938,
    "F": 18.998,
    "NO3": 62.0049,
    "H2SiO3": 78.11,    # explizit für H2SiO3 (nicht Si)
    "HS": 33.07,
}

def to_num(s):
    return pd.to_numeric(s, errors="coerce")

def mgL_to_mmolL(series, M_gmol):
    return to_num(series) / M_gmol

def mgL_to_umolL(series, M_gmol):
    return mgL_to_mmolL(series, M_gmol) * 1000.0

# -------------------------------------------------------------
# Einlesen
df = pd.read_csv(csv_path)

# Sicherstellen, dass alle Zielspalten existieren
for c in target_columns:
    if c not in df.columns:
        df[c] = np.nan

# -------------------------------------------------------------
# Umrechnungen (Annahme: in reflect_mapped.csv liegen die *_in_mmol/L bzw. *_in_umol/L
# noch als mg/L vor und müssen jetzt in die Ziel-Einheiten überführt werden.)

# mg/L -> mmol/L
mmol_map = {
    "O2_in_mmol/L":  "O2",
    "Na_in_mmol/L":  "Na",
    "Mg_in_mmol/L":  "Mg",
    "Ca_in_mmol/L":  "Ca",
    "Cl_in_mmol/L":  "Cl",
    "SO4_in_mmol/L": "SO4",
    "HCO3_in_mmol/L":"HCO3",
    "Li_in_mmol/L":  "Li",
    "K_in_mmol/L":   "K",
    "Fe_in_mmol/L":  "Fe",
    "Mn_in_mmol/L":  "Mn",
    "NO3_in_mmol/L": "NO3",
    "HS_in_mmol/L":  "HS",
}

for col, sp in mmol_map.items():
    if col in df.columns:
        df[col] = mgL_to_mmolL(df[col], M[sp])

# mg/L -> µmol/L (H2SiO3 jetzt wie die anderen µmol/L-Spalten behandeln)
umol_map = {
    "Sr_in_umol/L":   "Sr",
    "F_in_umol/L":    "F",
    "NH4_in_umol/L":  "NH4",
    "H2SiO3_in_umol/L": "H2SiO3",   # NEU: über 78.11 g/mol
}

for col, sp in umol_map.items():
    if col in df.columns:
        df[col] = mgL_to_umolL(df[col], M[sp])

# -------------------------------------------------------------
# TDS NEU berechnen: Summe aller anderen Ionen (in mmol/L)
# - mmols direkt summieren
# - umols vorher in mmol umrechnen (÷1000)
# - O2 NICHT auf TDS addieren (standardmäßig ausgeschlossen)
tds_mmols_cols = [
    "Na_in_mmol/L","Mg_in_mmol/L","Ca_in_mmol/L","Cl_in_mmol/L","SO4_in_mmol/L",
    "HCO3_in_mmol/L","Li_in_mmol/L","K_in_mmol/L","Fe_in_mmol/L","Mn_in_mmol/L",
    "NO3_in_mmol/L","HS_in_mmol/L"
]

tds_umols_cols = [
    "Sr_in_umol/L","F_in_umol/L","NH4_in_umol/L","H2SiO3_in_umol/L"
]

# Sicherstellen, dass Spalten existieren (falls nicht in CSV)
for c in tds_mmols_cols + tds_umols_cols:
    if c not in df.columns:
        df[c] = np.nan

tds_mmol_part = df[tds_mmols_cols].apply(pd.to_numeric, errors="coerce").fillna(0).sum(axis=1)
tds_umol_part = df[tds_umols_cols].apply(pd.to_numeric, errors="coerce").fillna(0).sum(axis=1) / 1000.0

df["total_dissolved_solids_in_mmol/L"] = tds_mmol_part + tds_umol_part

# -------------------------------------------------------------
# Ausgabe in Zielstruktur
after_conversion_reflect_path = os.path.join(mid_reflect_path, "after_conversion_reflect_mapped.csv")

df_out = df[target_columns].copy()
df_out.to_csv(after_conversion_reflect_path, index=False, encoding="utf-8-sig")

print(f"Einheiten-Umrechnung + TDS-Summenbildung abgeschlossen. Zeilen: {len(df_out)}")
print(f"Gespeichert: {after_conversion_reflect_path}")

Einheiten-Umrechnung + TDS-Summenbildung abgeschlossen. Zeilen: 5105
Gespeichert: C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\Zwischenstände\REFLECT_Datenbank\after_conversion_reflect_mapped.csv

In [16]:
csv_path = os.path.join(mid_reflect_path, "after_conversion_reflect_mapped.csv")
excel_path = os.path.join(mid_reflect_path, "after_conversion_reflect_mapped_readable.xlsx")

In [18]:
csv_to_excel(csv_path, excel_path)
output_path = os.path.join(base_dir, "Angepasste_Datenbanken")

Excel Pfad:
C:\Users\lucca\OneDrive\SPEICHER\Hochschule\7. Semester\Abschlussarbeit Bearbeitung\Jupyter Notebooks\1_Data-Acquisition-Wrapper\Zwischenstände\REFLECT_Datenbank\after_conversion_reflect_mapped_readable.xlsx

In [19]:
reflect_output_path = os.path.join(output_path, "REFLECT_cleaned_Database.csv")
df_out.to_csv(reflect_output_path, index=False, encoding="utf-8-sig")

<div class="alert alert-danger">
    <h1><b>DATENBANK 2</b></h1>
</div>